Update ru.wlist
GeyserMC/GeyserDiscordBot pull request #166
Opened 2021-08-18 12:49 UTC by MrZomka

Added plural and declension words and a few other words that I forgot to add to the list.

2021-08-19 08:45 UTC, rtm516 requested changes

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +блять
```suggestion
бля((д|т)ь)?
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +сучку
```suggestion
суч?к(и|у)
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +хуям
```suggestion
хуям?
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +епты
```suggestion
(ё|е)пт(а|ы)
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +пизду
```suggestion
пизд(а|е|ы|у)
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +пиздеца
```suggestion
пиздец(у|а)?
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +пидрам
```suggestion
пидр(у|ы|ам)?
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +пидорасину
```suggestion
пидорасин(у|а)
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +хую
```suggestion
ху(и|ю)
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +херам
```suggestion
хер(у|ам|а)?
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
>  ахуела
```suggestion
ахуел(и|а)?
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
>  ахерела
```suggestion
ахерел(и|а)?
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +хуепроебины
```suggestion
хуепро(ё|е)бин(а|у|е|ы|а)?
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +пидорам
```suggestion
пидор(у|ы|ам)?
```

2021-08-19 08:45 UTC, rtm516 commented on src/main/resources/filters/ru.wlist
> +пидорасу
```suggestion
пидора(су|с)?
```

2021-08-20 01:01 UTC, MrZomka reviewed
I did not know you can do that xD

2021-08-20 09:51 UTC, rtm516 approved these changes

2021-08-20 10:26 UTC, merged