Add button to clear embed if desired
GeyserMC/GeyserDiscordBot pull request #196
Opened 2021-11-08 00:48 UTC by Chew

Adds a button below error responses to remove the embed if the author of the original message or someone with manage messages wants to clear it.

2021-11-08 13:56 UTC, RednedEpic submitted a review, later dismissed

2021-11-08 17:39 UTC, Chew commented on src/main/java/org/geysermc/discordbot/listeners/InteractionHandler.java
> +        }
It's left there as a future placeholder in case we ever want to use it. It could be removed if we want

2022-01-22 00:47 UTC, Camotoy approved these changes

2022-01-22 00:51 UTC, Chew commented on src/main/java/org/geysermc/discordbot/listeners/InteractionHandler.java
> + * Copyright (c) 2020-2021 GeyserMC. http://geysermc.org
```suggestion
 * Copyright (c) 2020-2022 GeyserMC. http://geysermc.org
```

2022-08-10 19:35 UTC, rtm516 requested changes

2022-08-10 19:35 UTC, rtm516 commented on src/main/java/org/geysermc/discordbot/listeners/ErrorAnalyzer.java
> +            Button button = Button.secondary("listeners:error_analyzer:clear", Emoji.fromMarkdown("🗑"));
```suggestion
            Button button = Button.secondary("listeners:error_analyzer:clear", ":wastebasket:");
```

2022-08-28 16:17 UTC, Chew commented on src/main/java/org/geysermc/discordbot/listeners/ErrorAnalyzer.java
> +            Button button = Button.secondary("listeners:error_analyzer:clear", Emoji.fromMarkdown("🗑"));
What's the purpose of this?

2022-08-29 05:11 UTC, Chew commented
This should more than likely be converted to a context menu on the message at this point. Way less clunky. This already has unresolvable errors so I'll close this in favor of a new implementation.

2022-08-29 05:11 UTC, closed without merging