ORC support tool
GeyserMC/GeyserDiscordBot pull request #230
Opened 2022-06-01 14:37 UTC by Jens-Co

sudo apt install tesseract-ocr -y

main tessdata folder : /usr/share/tesseract-ocr/4.00/tessdata

Ill leave it as draft since there are some things still needed to be added.

2022-06-01 17:31 UTC, rtm516 requested changes

2022-06-01 18:13 UTC, Chew commented on src/main/java/org/geysermc/discordbot/storage/ServerSettings.java
> +     * @param channel The {@link TextChannel} to check
```suggestion
     * @param channel The {@link MessageChannel} to check
```

2022-06-01 18:13 UTC, Chew commented on src/main/java/org/geysermc/discordbot/storage/ServerSettings.java
> +        Guild guild = getGuild(channel);
We don't need to define this if we just check if it's null, do `getGuild(channel) == null` for example

2022-06-01 18:13 UTC, Chew commented on src/main/java/org/geysermc/discordbot/storage/ServerSettings.java
> +        List<String> dontLog = getList(channel.getIdLong(), "dont-checkerror");
Inline this call

2022-06-01 18:13 UTC, Chew commented on src/main/java/org/geysermc/discordbot/listeners/ErrorAnalyzer.java
> -
Don't remove this newline :(

2022-06-01 20:23 UTC, Jens-Co commented on src/main/java/org/geysermc/discordbot/listeners/ErrorAnalyzer.java
> +                    e.printStackTrace();
Not sure if what I did is something you would like.

2022-06-05 17:40 UTC, Jens-Co commented
To-Do: add a cooldown on image lookups.

2022-06-07 19:15 UTC, RednedEpic approved these changes

2022-06-07 19:20 UTC, merged