Stop dump handler from pinging localhost
GeyserMC/GeyserDiscordBot pull request #254
Opened 2022-10-02 19:39 UTC by Konicai

Bot can currently ping the test server right now.

2022-10-02 19:51 UTC, Konicai commented
Depends on #253

2022-10-06 18:28 UTC, Camotoy approved these changes

2022-10-06 18:28 UTC, Camotoy commented on src/main/java/org/geysermc/discordbot/commands/PingCommand.java
> +        if (DumpHandler.isInternalIP(hostname)) {
Maybe move this to a generic location.

2022-10-06 20:29 UTC, Konicai commented on src/main/java/org/geysermc/discordbot/commands/PingCommand.java
> +        if (DumpHandler.isInternalIP(hostname)) {
Agreed

2022-10-07 16:43 UTC, Konicai commented on src/main/java/org/geysermc/discordbot/commands/PingCommand.java
> +        if (DumpHandler.isInternalIP(hostname)) {
Updated

2022-10-08 01:03 UTC, rtm516 requested changes

2022-10-08 01:03 UTC, rtm516 commented on src/main/java/org/geysermc/discordbot/util/NetworkUtils.java
> +    public static final SubnetUtils.SubnetInfo[] INTERNAL_IP_RANGES = new SubnetUtils.SubnetInfo[] {
```suggestion
    private static final SubnetUtils.SubnetInfo[] INTERNAL_IP_RANGES = new SubnetUtils.SubnetInfo[] {
```

2022-10-08 01:03 UTC, rtm516 commented on src/test/java/org/geysermc/discordbot/commands/search/InternalIpTest.java
> +package org.geysermc.discordbot.commands.search;
This should be src/test/java/org/geysermc/discordbot/util/NetworkUtilsTest.java

2022-11-24 21:11 UTC, Tim203 approved these changes

2022-11-24 21:12 UTC, merged