Adding Github command.
GeyserMC/GeyserDiscordBot pull request #257
Opened 2022-10-03 21:50 UTC by Jens-Co

![image](https://user-images.githubusercontent.com/63231928/193692262-26a2c4a6-2b8c-4579-b112-522773ceb5f5.png)

2022-10-03 22:02 UTC, onebeastchris commented
yoooo, this is - again - sick! gone are the times when you had to manually search GitHub for a link

just to be sure, this just searches GitHub for repos matching the name? Or just the geyser/floodgate related one's?

2022-10-06 18:26 UTC, Camotoy commented
I feel like this should have two slash command string options: mandatory string for repository name, and optional string for owner/organization defaulting to GeyserMC.

2022-10-07 00:45 UTC, Jens-Co commented
> I feel like this should have two slash command string options: mandatory string for repository name, and optional string for owner/organization defaulting to GeyserMC.

https://github.com/GeyserMC/GeyserDiscordBot/commit/2d5b1f3606cfdba117edb96198f5ec55fe2703dc added an owner optional! Thanks.

2022-10-08 01:05 UTC, rtm516 requested changes
Just allowing the code to be a bit easier to read

2022-10-08 01:05 UTC, rtm516 commented on src/main/java/org/geysermc/discordbot/util/BotHelpers.java
> +        // if optional is used we get repo from optional first.
```suggestion

        // if optional is used we get repo from optional first.
```

2022-10-08 01:05 UTC, rtm516 commented on src/main/java/org/geysermc/discordbot/util/BotHelpers.java
> +        // if no owner is given search github repo's.
```suggestion

        // if no owner is given search github repo's.
```

2022-10-08 01:05 UTC, rtm516 commented on src/main/java/org/geysermc/discordbot/util/BotHelpers.java
> +        return repo;
```suggestion

        return repo;
```

2022-10-08 08:49 UTC, Jens-Co commented
> Just allowing the code to be a bit easier to read

Makes sense thanks!

2022-11-24 20:46 UTC, Tim203 approved these changes

2022-11-24 20:46 UTC, merged