Add GeyserOptionalPack tag.
GeyserMC/GeyserDiscordBot pull request #305
Opened 2024-02-05 09:12 UTC by hasankayra04

2024-07-31 23:44 UTC, onebeastchris requested changes

2024-07-31 23:44 UTC, onebeastchris commented on src/main/resources/tags/info/geyseroptionalpack.tag
> +Optional Bedrock resource pack to extend Geyser functionality. Learn more on its [wiki page](https://github.com/GeyserMC/Geyser/wiki/GeyserOptionalPack).
```suggestion
Optional Bedrock resource pack to extend Geyser functionality. Learn more on its [wiki page](https://geysermc.org/wiki/other/geyseroptionalpack/).
```

2024-07-31 23:44 UTC, onebeastchris commented on src/main/resources/tags/info/geyseroptionalpack.tag
> +aliases: gop
That sounds a bit too abstract - maybe just `optionalpack`?

2024-08-25 08:08 UTC, hasankayra04 commented
Adressed requested changes.

2024-08-25 08:14 UTC, onebeastchris approved these changes

2024-08-25 08:54 UTC, merged