Add MCXboxBroadcast tag
GeyserMC/GeyserDiscordBot pull request #318
Opened 2024-11-29 19:14 UTC by Novampr

Adds just one tag, for information on MCXboxBroadcast, which includes a link to RTM's server (getting one can be annoying) and provides a little information to the user on what it actually is.

2024-12-03 05:28 UTC, Chew requested changes
Just a few comments :)

2024-12-03 05:28 UTC, Chew commented on src/main/resources/tags/links/mcxboxbroadcast.tag
> +MCXboxBroadcast is tool for Geyser servers developed by <@170429173003714560>. It allows you to join a Geyser server by following or friending someone in Minecraft then joining that user.
```suggestion
MCXboxBroadcast is tool for Geyser servers developed by rtm516. It allows you to join a Geyser server by following or friending someone in Minecraft then joining that user.
```

Mentions don't render in embeds sometimes, so we can just say the name here

2024-12-03 05:28 UTC, Chew commented on src/main/resources/tags/links/mcxboxbroadcast.tag
> +It comes as a standalone application or an extension for Geyser, support is not typically provided here, however, there exists a support server linked below.
```suggestion
It comes as a standalone application or an extension for Geyser. Support is not typically provided here; however, there exists a support server linked below.
```

2024-12-05 07:42 UTC, lukeeey approved these changes

2024-12-05 22:29 UTC, Chew approved these changes
Approving based on grammar and spelling, anyone merging should verify factual content

2025-07-17 19:24 UTC, onebeastchris approved these changes

2025-07-18 22:35 UTC, rtm516 approved these changes

2025-07-18 22:36 UTC, merged